export const SEED_PRODUCTS = [
  {
    sku: "TS-PRO-001",
    name: "Commit & Pray",
    series: "profesi",
    seriesName: "TeeStock Profesi",
    niche: "Software Engineer / IT",
    priceRetail: 99000,
    priceReseller: 75000,
    costBlank: 38000,
    costDtf: 12750,
    filePath: "https://images.unsplash.com/photo-1521572267360-ee0c2909d518?w=800&auto=format&fit=crop&q=80",
    description: "Kaos streetwear minimalis bertema developer dan programmer. Bahan NSA Softstyle 30s 100% cotton adem dan sablon DTF HD tajam tahan cuci.",
    status: "active",
    featured: true
  },
  {
    sku: "TS-PRO-002",
    name: "Architect's Blueprint",
    series: "profesi",
    seriesName: "TeeStock Profesi",
    niche: "Arsitek & Desainer",
    priceRetail: 109000,
    priceReseller: 82000,
    costBlank: 48000,
    costDtf: 12750,
    filePath: "https://images.unsplash.com/photo-1503342217505-b0a15ec3261c?w=800&auto=format&fit=crop&q=80",
    description: "Visual garis isometrik denah arsitektur di atas bahan tebal NSA Heavyweight 24s. Potongan boxy modern yang nyaman dipakai seharian di proyek maupun studio.",
    status: "active",
    featured: true
  },
  {
    sku: "TS-KOM-001",
    name: "7 Summits 3000 MDPL",
    series: "komunitas",
    seriesName: "TeeStock Komunitas / Aktif",
    niche: "Pendaki Gunung / Hiking",
    priceRetail: 99000,
    priceReseller: 75000,
    costBlank: 38000,
    costDtf: 12750,
    filePath: "https://images.unsplash.com/photo-1576566588028-4147f3842f27?w=800&auto=format&fit=crop&q=80",
    description: "Ilustrasi kontur topografi puncak-puncak tertinggi Nusantara. Dedikasi untuk jiwa-jiwa petualang alam bebas.",
    status: "active",
    featured: true
  },
  {
    sku: "TS-LOK-001",
    name: "Wong Jowo Ojo Ilang Jawane",
    series: "lokal",
    seriesName: "TeeStock Lokal",
    niche: "Filosofi Jawa / Budaya",
    priceRetail: 89000,
    priceReseller: 68000,
    costBlank: 38000,
    costDtf: 12750,
    filePath: "https://images.unsplash.com/photo-1618354691373-d851c5c3a990?w=800&auto=format&fit=crop&q=80",
    description: "Aksara Jawa stilasi modern dengan pesan pengingat akar budaya luhur. Elegan dan bermakna mendalam.",
    status: "active",
    featured: true
  },
  {
    sku: "TS-REC-001",
    name: "Crisis with Iced Coffee",
    series: "receh",
    seriesName: "TeeStock Receh / Sarkas",
    niche: "Kopi & Gaya Hidup",
    priceRetail: 99000,
    priceReseller: 75000,
    costBlank: 38000,
    costDtf: 12750,
    filePath: "https://images.unsplash.com/photo-1521572267360-ee0c2909d518?w=800&auto=format&fit=crop&q=80",
    description: "Menghadapi hari berat dengan secangkir es kopi susu gula aren. Santai, jenaka, dan sangat relatable.",
    status: "active",
    featured: false
  },
  {
    sku: "TS-FAN-001",
    name: "Neo Tokyo 1988",
    series: "fandom",
    seriesName: "TeeStock Fandom",
    niche: "Retro Anime & Cyberpunk",
    priceRetail: 109000,
    priceReseller: 82000,
    costBlank: 48000,
    costDtf: 12750,
    filePath: "https://images.unsplash.com/photo-1503342217505-b0a15ec3261c?w=800&auto=format&fit=crop&q=80",
    description: "Estetika anime retro cyberpunk 80-an dengan cetakan DTF warna neon di atas kaos NSA Heavyweight 24s hitam pekat.",
    status: "active",
    featured: true
  },
  {
    sku: "TS-BLK-3600",
    name: "New States Apparel Softstyle 3600",
    series: "blank",
    seriesName: "NSA Blank Apparel",
    niche: "Kaos Polos Ring Spun 30s Tubular",
    cititexCatId: 87,
    priceRetail: 49000,
    priceReseller: 42000,
    costBlank: 38000,
    costDtf: 0,
    costPress: 0,
    costPack: 3500,
    costOverhead: 1500,
    filePath: "https://cititex.com/api/uploads/category/album/front_side/87-Black.jpg",
    description: "Kaos polos New States Apparel Softstyle 3600. 100% Ring Spun Cotton 30s, 150 g/m2. Lembut, adem, jahitan rantai rapi tanpa jahitan samping (tubular/built-up). Cocok untuk daily casual wear maupun disablon DTF.",
    colors: "Hitam, Putih, Charcoal, Navy, Maroon, Sport Grey, Forest Green, Royal Blue, Red, Irish Green, Daisy, Heliconia, Sand, Orange, Mustard",
    sizes: "S, M, L, XL, XXL, 3XL",
    status: "active",
    featured: true
  },
  {
    sku: "TS-BLK-7200",
    name: "New States Apparel Premium Cotton 7200",
    series: "blank",
    seriesName: "NSA Blank Apparel",
    niche: "Kaos Polos Combed 24s Regular Fit",
    cititexCatId: 99,
    priceRetail: 59000,
    priceReseller: 51000,
    costBlank: 48000,
    costDtf: 0,
    costPress: 0,
    costPack: 3500,
    costOverhead: 1500,
    filePath: "https://cititex.com/api/uploads/category/album/front_side/99-Black.jpg",
    description: "Kaos polos New States Apparel Premium Cotton 7200. 100% Cotton Combed 24s, 180 g/m2. Bahan lebih tebal, kokoh, dan presisi. Potongan regular fit dengan kenyamanan premium.",
    colors: "Black, White, Navy, Maroon, Sport Grey, Forest Green, Charcoal, Salmon, Aqua Sky, Gold, Royal Blue, Red",
    sizes: "S, M, L, XL, XXL, 3XL",
    status: "active",
    featured: true
  },
  {
    sku: "TS-BLK-5400",
    name: "New States Apparel Heavyweight 5400",
    series: "blank",
    seriesName: "NSA Blank Apparel",
    niche: "Kaos Polos Streetwear 20s Boxy Fit",
    cititexCatId: 95,
    priceRetail: 79000,
    priceReseller: 69000,
    costBlank: 65000,
    costDtf: 0,
    costPress: 0,
    costPack: 3500,
    costOverhead: 1500,
    filePath: "https://cititex.com/api/uploads/category/album/front_side/95-Black.jpg",
    description: "Kaos polos New States Apparel Heavyweight 5400. 100% Cotton 20s, 210 g/m2. Karakter kain berat, kaku, dan tebal khas streetwear boxy vintage look. Kerah leher tebal anti-melar.",
    colors: "Black, White, Navy, Sport Grey, Maroon, Gold, Dark Green",
    sizes: "S, M, L, XL, XXL, 3XL",
    status: "active",
    featured: true
  },
  {
    sku: "TS-BLK-7280",
    name: "New States Apparel Long Sleeve 7280",
    series: "blank",
    seriesName: "NSA Blank Apparel",
    niche: "Kaos Polos Lengan Panjang Rib 24s",
    cititexCatId: 94,
    priceRetail: 69000,
    priceReseller: 59000,
    costBlank: 55000,
    costDtf: 0,
    costPress: 0,
    costPack: 3500,
    costOverhead: 1500,
    filePath: "https://cititex.com/api/uploads/category/album/front_side/94-Black.jpg",
    description: "Kaos polos New States Apparel Premium Cotton Long Sleeve 7280. 100% Cotton 24s dengan rib manset elastis di pergelangan tangan. Melindungi dari sinar matahari dan udara dingin.",
    colors: "Black, White, Navy, Sport Grey, Maroon, Charcoal, Forest Green",
    sizes: "S, M, L, XL, XXL, 3XL",
    status: "active",
    featured: false
  },
  {
    sku: "TS-BLK-5480",
    name: "New States Apparel Heavyweight Long Sleeve 5480",
    series: "blank",
    seriesName: "NSA Blank Apparel",
    niche: "Kaos Polos Lengan Panjang 20s Heavy",
    cititexCatId: 124,
    priceRetail: 89000,
    priceReseller: 78000,
    costBlank: 72000,
    costDtf: 0,
    costPress: 0,
    costPack: 3500,
    costOverhead: 1500,
    filePath: "https://cititex.com/api/uploads/category/album/front_side/124-Black.jpg",
    description: "Kaos lengan panjang New States Apparel Heavyweight 5480. Bahan tebal 20s, potongan boxier fit dengan manset rib rapat. Sangat dicari untuk gaya streetwear musim sejuk.",
    colors: "Black, White, Sport Grey, Navy",
    sizes: "S, M, L, XL, XXL",
    status: "active",
    featured: false
  },
  {
    sku: "TS-BLK-7250",
    name: "New States Apparel Ringer Tee 7250",
    series: "blank",
    seriesName: "NSA Blank Apparel",
    niche: "Kaos Polos Retro Ringer Dua Warna",
    cititexCatId: 97,
    priceRetail: 59000,
    priceReseller: 50000,
    costBlank: 45000,
    costDtf: 0,
    costPress: 0,
    costPack: 3500,
    costOverhead: 1500,
    filePath: "https://cititex.com/api/uploads/category/album/front_side/97-White-Black.jpg",
    description: "Kaos polos New States Apparel Premium Cotton Ringer 7250. Desain retro vintage dengan kombinasi rib leher dan lengan berbeda warna. 100% Combed Cotton 24s lembut.",
    colors: "White-Black, White-Red, White-Navy, White-Forest Green, White-Gold, Sport Grey-Black",
    sizes: "S, M, L, XL, XXL",
    status: "active",
    featured: false
  },
  {
    sku: "TS-BLK-7260",
    name: "New States Apparel Raglan 3/4 7260",
    series: "blank",
    seriesName: "NSA Blank Apparel",
    niche: "Kaos Polos Raglan Tiga Perempat",
    cititexCatId: 98,
    priceRetail: 72000,
    priceReseller: 63000,
    costBlank: 58000,
    costDtf: 0,
    costPress: 0,
    costPack: 3500,
    costOverhead: 1500,
    filePath: "https://cititex.com/api/uploads/category/album/front_side/98-White-Black.jpg",
    description: "Kaos polos New States Apparel Premium Cotton Raglan 3/4 7260. Potongan lengan raglan diagonal 3/4 klasik. Bahan katun 24s nyaman untuk aktivitas kasual dan santai.",
    colors: "White-Black, White-Red, White-Navy, White-Forest Green, Sport Grey-Black, Sport Grey-Navy",
    sizes: "S, M, L, XL, XXL",
    status: "active",
    featured: false
  },
  {
    sku: "TS-BLK-8100",
    name: "New States Apparel Polo Shirt 8100",
    series: "blank",
    seriesName: "NSA Blank Apparel",
    niche: "Wangki Polo Pique Cotton Berkerah",
    cititexCatId: 96,
    priceRetail: 89000,
    priceReseller: 76000,
    costBlank: 68000,
    costDtf: 0,
    costPress: 0,
    costPack: 3500,
    costOverhead: 1500,
    filePath: "https://cititex.com/api/uploads/category/album/front_side/96-Black.jpg",
    description: "Kaos polo New States Apparel Premium Cotton Polo Shirt 8100. Rajutan kain pique pori klasik dengan 2 kancing berukir elegan. Rapi untuk seragam kantor dan event semi-formal.",
    colors: "Black, White, Navy, Red, Maroon, Sport Grey, Royal Blue, Forest Green",
    sizes: "S, M, L, XL, XXL",
    status: "active",
    featured: false
  },
  {
    sku: "TS-BLK-9500",
    name: "New States Apparel Hoodie 9500",
    series: "blank",
    seriesName: "NSA Blank Apparel",
    niche: "Sweatshirt Hoodie Fleece Tebal",
    cititexCatId: 103,
    priceRetail: 165000,
    priceReseller: 142000,
    costBlank: 125000,
    costDtf: 0,
    costPress: 0,
    costPack: 4500,
    costOverhead: 2000,
    filePath: "https://cititex.com/api/uploads/category/album/front_side/103-Black.jpg",
    description: "Jaket hoodie New States Apparel Super Blend Hooded Sweatshirt 9500. 50% Cotton / 50% Polyester Fleece 270 g/m2. Kantung kangguru ganda, tali serut senada, permukaan luar halus dan dalam hangat lembut.",
    colors: "Black, Sport Grey, Navy, Maroon, Forest Green",
    sizes: "S, M, L, XL, XXL",
    status: "active",
    featured: true
  },
  {
    sku: "TS-BLK-9000",
    name: "New States Apparel Crewneck 9000",
    series: "blank",
    seriesName: "NSA Blank Apparel",
    niche: "Sweatshirt Crewneck Fleece Kerah Bulat",
    cititexCatId: 118,
    priceRetail: 145000,
    priceReseller: 125000,
    costBlank: 110000,
    costDtf: 0,
    costPress: 0,
    costPack: 4500,
    costOverhead: 2000,
    filePath: "https://cititex.com/api/uploads/category/album/front_side/118-Black.jpg",
    description: "Sweatshirt kerah bulat New States Apparel Super Blend Crewneck 9000. Bahan fleece katun premium 270 g/m2 tanpa tudung. Manset rib rajut tebal dan jahitan ganda kokoh.",
    colors: "Black, Sport Grey, Navy, Maroon",
    sizes: "S, M, L, XL, XXL",
    status: "active",
    featured: false
  },
  {
    sku: "TS-BLK-2700",
    name: "New States Apparel Performance Dri-Fit 2700",
    series: "blank",
    seriesName: "NSA Blank Apparel",
    niche: "Kaos Olahraga Quick-Dry Performance",
    cititexCatId: 130,
    priceRetail: 47000,
    priceReseller: 39000,
    costBlank: 35000,
    costDtf: 0,
    costPress: 0,
    costPack: 3500,
    costOverhead: 1500,
    filePath: "https://cititex.com/api/uploads/category/album/front_side/130-Black.jpg",
    description: "Kaos olahraga New States Apparel Performance Dri-Fit 2700. 100% Polyester micro-mesh pori halus. Cepat kering (quick-dry), sejuk, dan elastis. Pilihan terbaik untuk running, gym, dan futsal.",
    colors: "Black, White, Navy, Red, Royal Blue, Neon Green",
    sizes: "S, M, L, XL, XXL",
    status: "active",
    featured: false
  },
  {
    sku: "TS-BLK-72Y00",
    name: "New States Apparel Youth T-Shirt 72Y00",
    series: "blank",
    seriesName: "NSA Blank Apparel",
    niche: "Kaos Polos Anak Katun Combed 24s",
    cititexCatId: 129,
    priceRetail: 47000,
    priceReseller: 39000,
    costBlank: 35000,
    costDtf: 0,
    costPress: 0,
    costPack: 3500,
    costOverhead: 1500,
    filePath: "https://cititex.com/api/uploads/category/album/front_side/129-Black.jpg",
    description: "Kaos polos anak New States Apparel Youth 72Y00. 100% Premium Cotton Combed 24s aman dan nyaman untuk kulit anak-anak. Kerah rib elastis dan tanpa jahitan samping.",
    colors: "Black, White, Navy, Red, Royal Blue, Daisy, Heliconia",
    sizes: "YXS, YS, YM, YL, YXL",
    status: "active",
    featured: false
  }
];

export const SEED_ORDERS = [
  {
    id: "SHP-2609-001",
    customer: "Dimas Arya",
    phone: "0812-9821-4411",
    city: "Jakarta Selatan",
    channel: "shopee",
    sku: "TS-PRO-001",
    productName: "Commit & Pray",
    garment: "NSA Softstyle 30s",
    color: "Hitam",
    size: "L",
    qty: 1,
    price: 99000,
    fee: 6435,
    status: "pending",
    date: "2026-09-04 14:20"
  },
  {
    id: "SHP-2609-002",
    customer: "Reza Fahlevi",
    phone: "0857-1122-3344",
    city: "Bandung",
    channel: "shopee",
    sku: "TS-KOM-001",
    productName: "7 Summits 3000 MDPL",
    garment: "NSA Softstyle 30s",
    color: "Olive",
    size: "XL",
    qty: 1,
    price: 99000,
    fee: 6435,
    status: "dtf",
    date: "2026-09-04 15:10"
  },
  {
    id: "WA-2609-003",
    customer: "Komunitas Kopi Pagi",
    phone: "0818-4455-6677",
    city: "Yogyakarta",
    channel: "whatsapp",
    sku: "TS-REC-001",
    productName: "Crisis with Iced Coffee",
    garment: "NSA Heavyweight 24s",
    color: "Krem",
    size: "M",
    qty: 2,
    price: 210000,
    fee: 0,
    status: "press",
    date: "2026-09-04 16:05"
  },
  {
    id: "WEB-2609-004",
    customer: "Andi Wijaya",
    phone: "0821-8899-0011",
    city: "Surabaya",
    channel: "web",
    sku: "TS-LOK-001",
    productName: "Wong Jowo Ojo Ilang",
    garment: "NSA Softstyle 30s",
    color: "Hitam",
    size: "L",
    qty: 1,
    price: 89000,
    fee: 1335,
    status: "pack",
    date: "2026-09-04 17:45"
  }
];

export const INITIAL_INVENTORY_MATRIX = {
  nsa_softstyle_30s: {
    Hitam:      { S: 4, M: 8, L: 10, XL: 6, XXL: 3, "3XL": 2 },
    Krem:       { S: 2, M: 5, L: 6,  XL: 4, XXL: 2, "3XL": 1 },
    Charcoal:   { S: 3, M: 4, L: 5,  XL: 3, XXL: 1, "3XL": 1 },
    Olive:      { S: 2, M: 4, L: 5,  XL: 3, XXL: 2, "3XL": 1 },
    Navy:       { S: 2, M: 3, L: 4,  XL: 2, XXL: 1, "3XL": 1 },
    Terracotta: { S: 1, M: 3, L: 4,  XL: 2, XXL: 1, "3XL": 0 },
    Putih:      { S: 3, M: 6, L: 6,  XL: 4, XXL: 2, "3XL": 1 }
  },
  nsa_heavyweight_24s: {
    Hitam:    { S: 3, M: 6, L: 8, XL: 5, XXL: 2, "3XL": 1 },
    Krem:     { S: 2, M: 4, L: 5, XL: 3, XXL: 1, "3XL": 1 },
    Charcoal: { S: 2, M: 3, L: 4, XL: 2, XXL: 1, "3XL": 1 },
    Olive:    { S: 1, M: 2, L: 3, XL: 2, XXL: 1, "3XL": 0 },
    Navy:     { S: 1, M: 2, L: 3, XL: 1, XXL: 1, "3XL": 0 }
  },
  nsa_longsleeve: {
    Hitam:    { S: 2, M: 4, L: 5, XL: 3, XXL: 1, "3XL": 1 },
    Putih:    { S: 1, M: 3, L: 3, XL: 2, XXL: 1, "3XL": 0 },
    Navy:     { S: 1, M: 2, L: 2, XL: 1, XXL: 1, "3XL": 0 },
    Charcoal: { S: 1, M: 2, L: 2, XL: 1, XXL: 0, "3XL": 0 }
  },
  nsa_hoodie: {
    Hitam:    { S: 1, M: 3, L: 4, XL: 3, XXL: 1, "3XL": 1 },
    Charcoal: { S: 1, M: 2, L: 2, XL: 2, XXL: 1, "3XL": 0 },
    Navy:     { S: 0, M: 2, L: 2, XL: 1, XXL: 1, "3XL": 0 }
  },
  nsa_polo: {
    Hitam: { S: 2, M: 3, L: 4, XL: 2, XXL: 1, "3XL": 1 },
    Navy:  { S: 1, M: 2, L: 3, XL: 2, XXL: 1, "3XL": 0 },
    Putih: { S: 1, M: 2, L: 2, XL: 1, XXL: 1, "3XL": 0 }
  },
  supplies: {
    "Polymailer Tebal (30x40 cm)": { Ready: 120, Min: 30 },
    "Hangtag Distro TeeStock":     { Ready: 250, Min: 50 },
    "Stiker Vinyl Pack TeeStock":  { Ready: 180, Min: 40 },
    "Kertas Roti Baking Paper":    { Ready: 45,  Min: 10 },
    "Lakban Fragile Merah":        { Ready: 6,   Min: 2  }
  }
};
