export const SEED_PRODUCTS = [
  {
    sku: "TS-PRO-001",
    name: "Commit & Pray",
    series: "profesi",
    seriesName: "TeeStock Profesi",
    niche: "Software Engineer / IT",
    priceRetail: 99000,
    priceReseller: 75000,
    costBlank: 38000,
    costDtf: 12750,
    colors: "Hitam, Putih, Charcoal, Navy",
    filePath: "https://images.unsplash.com/photo-1521572267360-ee0c2909d518?w=800&auto=format&fit=crop&q=80",
    description: "Kaos streetwear minimalis bertema developer dan programmer. Bahan NSA Softstyle 30s 100% cotton adem dan sablon DTF HD tajam tahan cuci.",
    status: "active",
    featured: true
  },
  {
    sku: "TS-PRO-002",
    name: "Architect's Blueprint",
    series: "profesi",
    seriesName: "TeeStock Profesi",
    niche: "Arsitek & Desainer",
    priceRetail: 109000,
    priceReseller: 82000,
    costBlank: 48000,
    costDtf: 12750,
    colors: "Hitam, Charcoal, Putih, Olive",
    filePath: "https://images.unsplash.com/photo-1503342217505-b0a15ec3261c?w=800&auto=format&fit=crop&q=80",
    description: "Visual garis isometrik denah arsitektur di atas bahan tebal NSA Heavyweight 24s. Potongan boxy modern yang nyaman dipakai seharian di proyek maupun studio.",
    status: "active",
    featured: true
  },
  {
    sku: "TS-KOM-001",
    name: "7 Summits 3000 MDPL",
    series: "komunitas",
    seriesName: "TeeStock Komunitas / Aktif",
    niche: "Pendaki Gunung / Hiking",
    priceRetail: 99000,
    priceReseller: 75000,
    costBlank: 38000,
    costDtf: 12750,
    colors: "Forest Green, Hitam, Charcoal, Sand",
    filePath: "https://images.unsplash.com/photo-1576566588028-4147f3842f27?w=800&auto=format&fit=crop&q=80",
    description: "Ilustrasi kontur topografi puncak-puncak tertinggi Nusantara. Dedikasi untuk jiwa-jiwa petualang alam bebas.",
    status: "active",
    featured: true
  },
  {
    sku: "TS-LOK-001",
    name: "Wong Jowo Ojo Ilang Jawane",
    series: "lokal",
    seriesName: "TeeStock Lokal",
    niche: "Filosofi Jawa / Budaya",
    priceRetail: 89000,
    priceReseller: 68000,
    costBlank: 38000,
    costDtf: 12750,
    colors: "Hitam, Maroon, Terracotta, Putih",
    filePath: "https://images.unsplash.com/photo-1618354691373-d851c5c3a990?w=800&auto=format&fit=crop&q=80",
    description: "Aksara Jawa stilasi modern dengan pesan pengingat akar budaya luhur. Elegan dan bermakna mendalam.",
    status: "active",
    featured: true
  },
  {
    sku: "TS-REC-001",
    name: "Crisis with Iced Coffee",
    series: "receh",
    seriesName: "TeeStock Receh / Sarkas",
    niche: "Kopi & Gaya Hidup",
    priceRetail: 99000,
    priceReseller: 75000,
    costBlank: 38000,
    costDtf: 12750,
    colors: "Hitam, Putih, Krem, Charcoal",
    filePath: "https://images.unsplash.com/photo-1521572267360-ee0c2909d518?w=800&auto=format&fit=crop&q=80",
    description: "Menghadapi hari berat dengan secangkir es kopi susu gula aren. Santai, jenaka, dan sangat relatable.",
    status: "active",
    featured: false
  },
  {
    sku: "TS-FAN-001",
    name: "Neo Tokyo 1988",
    series: "fandom",
    seriesName: "TeeStock Fandom",
    niche: "Retro Anime & Cyberpunk",
    priceRetail: 109000,
    priceReseller: 82000,
    costBlank: 48000,
    costDtf: 12750,
    colors: "Hitam, Charcoal, Navy",
    filePath: "https://images.unsplash.com/photo-1503342217505-b0a15ec3261c?w=800&auto=format&fit=crop&q=80",
    description: "Estetika anime retro cyberpunk 80-an dengan cetakan DTF warna neon di atas kaos NSA Heavyweight 24s hitam pekat.",
    status: "active",
    featured: true
  },
  {
    sku: "TS-BLK-3600",
    name: "New States Apparel Softstyle 3600",
    series: "blank",
    seriesName: "NSA Blank Apparel",
    niche: "Kaos Polos Ring Spun 30s Tubular",
    cititexCatId: 87,
    priceRetail: 49000,
    priceReseller: 42000,
    costBlank: 38000,
    costDtf: 0,
    costPress: 0,
    costPack: 3500,
    costOverhead: 1500,
    filePath: "https://cititex.com/api/uploads/category/album/front_side/87-White.jpg",
    description: "Kaos polos New States Apparel Softstyle 3600. 100% Ring Spun Cotton 30s, 150 g/m2. Lembut, adem, jahitan rantai rapi tanpa jahitan samping (tubular/built-up). Cocok untuk daily casual wear maupun disablon DTF.",
    colors: "White, Black, Red, Navy, Royal Blue, Maroon, Irish Green, Sport Grey, Charcoal, Forest Green, Dark Chocolate, Daisy, Heliconia, Orange, Sand, Carolina Blue, Lime, Light Pink, Sapphire, Purple, Gold, Chestnut, Military Green, Aqua Sky, Butter, Green Ash, Salmon, Lilac",
    sizes: "S, M, L, XL, XXL, 3XL",
    status: "active",
    featured: true
  },
  {
    sku: "TS-BLK-7280",
    name: "New States Apparel Long Sleeve 7280",
    series: "blank",
    seriesName: "NSA Blank Apparel",
    niche: "Kaos Polos Lengan Panjang Rib 24s",
    cititexCatId: 94,
    priceRetail: 69000,
    priceReseller: 59000,
    costBlank: 55000,
    costDtf: 0,
    costPress: 0,
    costPack: 3500,
    costOverhead: 1500,
    filePath: "https://cititex.com/api/uploads/category/album/front_side/94-Black.jpg",
    description: "Kaos polos New States Apparel Premium Cotton Long Sleeve 7280. 100% Cotton 24s dengan rib manset elastis di pergelangan tangan. Melindungi dari sinar matahari dan udara dingin.",
    colors: "Black, White, Sport Grey, Navy, Maroon, Forest Green, Royal Blue, Red, Gold, Dark Chocolate, Charcoal, Military Green, Carolina Blue, Orange, Light Pink, Irish Green, Daisy, Sand, Purple, Lilac, Salmon, Aqua Sky, Green Ash, Butter, Chestnut, Heliconia, Sapphire, Black Heather, Burgundy Heather, Dark Green Heather, Navy Heather, Red Heather, Mustard, Lime",
    sizes: "S, M, L, XL, XXL, 3XL",
    status: "active",
    featured: false
  },
  {
    sku: "TS-BLK-5400",
    name: "New States Apparel Heavyweight 5400",
    series: "blank",
    seriesName: "NSA Blank Apparel",
    niche: "Kaos Polos Streetwear 20s Boxy Fit",
    cititexCatId: 95,
    priceRetail: 79000,
    priceReseller: 69000,
    costBlank: 65000,
    costDtf: 0,
    costPress: 0,
    costPack: 3500,
    costOverhead: 1500,
    filePath: "https://cititex.com/api/uploads/category/album/front_side/95-Black.jpg",
    description: "Kaos polos New States Apparel Heavyweight 5400. 100% Cotton 20s, 210 g/m2. Karakter kain berat, kaku, dan tebal khas streetwear boxy vintage look. Kerah leher tebal anti-melar.",
    colors: "Black, White, Sport Grey, Navy, Maroon, Gold, Red, Royal Blue",
    sizes: "S, M, L, XL, XXL, 3XL",
    status: "active",
    featured: true
  },
  {
    sku: "TS-BLK-8100",
    name: "New States Apparel Polo Shirt 8100",
    series: "blank",
    seriesName: "NSA Blank Apparel",
    niche: "Wangki Polo Pique Cotton Berkerah",
    cititexCatId: 96,
    priceRetail: 89000,
    priceReseller: 78000,
    costBlank: 68000,
    costDtf: 0,
    costPress: 0,
    costPack: 3500,
    costOverhead: 1500,
    filePath: "https://cititex.com/api/uploads/category/album/front_side/96-Black.jpg",
    description: "Baju polo New States Apparel 8100. Pique cotton berpori halus dengan kerah rajut kokoh dan 2 kancing depan. Gaya smart-casual semi-formal untuk santai maupun kantor.",
    colors: "Black, White, Sport Grey, Navy, Maroon, Royal Blue, Red, Irish Green, Orange, Daisy, Light Pink, Charcoal, Carolina Blue, Forest Green",
    sizes: "S, M, L, XL, XXL",
    status: "active",
    featured: false
  },
  {
    sku: "TS-BLK-7250",
    name: "New States Apparel Ringer Tee 7250",
    series: "blank",
    seriesName: "NSA Blank Apparel",
    niche: "Kaos Vintage Ringer Retro 24s",
    cititexCatId: 97,
    priceRetail: 59000,
    priceReseller: 50000,
    costBlank: 45000,
    costDtf: 0,
    costPress: 0,
    costPack: 3500,
    costOverhead: 1500,
    filePath: "https://cititex.com/api/uploads/category/album/front_side/97-White-Black.jpg",
    description: "Kaos retro New States Apparel Ringer Tee 7250. Bahan 24s combed lembut dengan aksen warna kontras pada rib leher dan rib lengan. Tampilan vintage khas era 80-an.",
    colors: "White-Black, White-Navy, White-Maroon, White-Red, White-Forest Green, White-Gold, White-Royal Blue, Sport Grey-Black, Sport Grey-Navy, Sport Grey-Maroon, Sport Grey-Red",
    sizes: "S, M, L, XL, XXL",
    status: "active",
    featured: false
  },
  {
    sku: "TS-BLK-7260",
    name: "New States Apparel Raglan 3/4 7260",
    series: "blank",
    seriesName: "NSA Blank Apparel",
    niche: "Kaos Raglan Tiga Perempat 24s",
    cititexCatId: 98,
    priceRetail: 72000,
    priceReseller: 62000,
    costBlank: 58000,
    costDtf: 0,
    costPress: 0,
    costPack: 3500,
    costOverhead: 1500,
    filePath: "https://cititex.com/api/uploads/category/album/front_side/98-White-Black.jpg",
    description: "Kaos New States Apparel Raglan 3/4 7260. Kombinasi potongan lengan raglan diagonal dengan panjang lengan 3/4. Terbuat dari katun combed 24s bertekstur lembut.",
    colors: "White-Black, White-Navy, White-Maroon, White-Red, White-Forest Green, White-Charcoal, White-Royal Blue, Sport Grey-Black, Sport Grey-Navy, Sport Grey-Maroon, Sport Grey-Red",
    sizes: "S, M, L, XL, XXL",
    status: "active",
    featured: false
  },
  {
    sku: "TS-BLK-7200",
    name: "New States Apparel Premium Cotton 7200",
    series: "blank",
    seriesName: "NSA Blank Apparel",
    niche: "Kaos Polos Combed 24s Regular Fit",
    cititexCatId: 99,
    priceRetail: 59000,
    priceReseller: 51000,
    costBlank: 48000,
    costDtf: 0,
    costPress: 0,
    costPack: 3500,
    costOverhead: 1500,
    filePath: "https://cititex.com/api/uploads/category/album/front_side/99-Black.jpg",
    description: "Kaos polos New States Apparel Premium Cotton 7200. 100% Cotton Combed 24s, 180 g/m2. Bahan lebih tebal, kokoh, dan presisi. Potongan regular fit dengan kenyamanan premium.",
    colors: "Black, White, Sport Grey, Navy, Maroon, Red, Royal Blue, Irish Green, Daisy, Forest Green, Charcoal, Gold, Dark Chocolate, Military Green, Carolina Blue, Orange, Light Pink, Sand, Purple, Black Heather, Navy Heather, Red Heather, Dark Green Heather, Burgundy Heather, Aqua Sky, Butter, Green Ash, Lilac, Salmon, Mustard, Lime, Chestnut, Sapphire, Heliconia",
    sizes: "S, M, L, XL, XXL, 3XL",
    status: "active",
    featured: true
  },
  {
    sku: "TS-BLK-9600",
    name: "New States Apparel Full Zip Hoodie 9600",
    series: "blank",
    seriesName: "NSA Blank Apparel",
    niche: "Jaket Hoodie Resleting Depan 270 gsm",
    cititexCatId: 102,
    priceRetail: 179000,
    priceReseller: 155000,
    costBlank: 135000,
    costDtf: 0,
    costPress: 0,
    costPack: 3500,
    costOverhead: 1500,
    filePath: "https://cititex.com/api/uploads/category/album/front_side/102-Black.jpg",
    description: "Jaket hoodie New States Apparel 9600 dengan resleting depan penuh YKK berkualitas tinggi. Bahan fleece katun lembut 270 g/m2 dengan tudung ganda dan kantong saku praktis.",
    colors: "Black, Navy, Sport Grey, Maroon, Black Camo, Forest Camo, Forest Green",
    sizes: "S, M, L, XL, XXL",
    status: "active",
    featured: false
  },
  {
    sku: "TS-BLK-9500",
    name: "New States Apparel Hoodie 9500",
    series: "blank",
    seriesName: "NSA Blank Apparel",
    niche: "Jaket Hoodie Fleece Pullover 270 gsm",
    cititexCatId: 103,
    priceRetail: 165000,
    priceReseller: 145000,
    costBlank: 125000,
    costDtf: 0,
    costPress: 0,
    costPack: 3500,
    costOverhead: 1500,
    filePath: "https://cititex.com/api/uploads/category/album/front_side/103-Black.jpg",
    description: "Jaket hoodie New States Apparel 9500 model pullover. Fleece tebal 270 g/m2 (50% cotton / 50% polyester). Kantung kangguru depan yang luas dengan tali serut bertudung ganda.",
    colors: "Black, Navy, Sport Grey, Maroon, Black Camo, Forest Camo, Forest Green, Red, Gold, Army, Royal Blue, Lilac, White, Light Blue, Light Pink",
    sizes: "S, M, L, XL, XXL",
    status: "active",
    featured: true
  },
  {
    sku: "TS-BLK-9000",
    name: "New States Apparel Crewneck 9000",
    series: "blank",
    seriesName: "NSA Blank Apparel",
    niche: "Sweatshirt Fleece Kerah Bulat 270 gsm",
    cititexCatId: 118,
    priceRetail: 145000,
    priceReseller: 125000,
    costBlank: 110000,
    costDtf: 0,
    costPress: 0,
    costPack: 3500,
    costOverhead: 1500,
    filePath: "https://cititex.com/api/uploads/category/album/front_side/118-Black.jpg",
    description: "Sweatshirt New States Apparel Crewneck 9000. Bahan fleece katun hangat 270 g/m2 tanpa tudung. Manset rib elastis pada leher, lengan, dan pinggang.",
    colors: "Black, Navy, Sport Grey, Maroon, White, Red, Forest Green, Black Camo, Forest Camo, Royal Blue, Army, Light Pink",
    sizes: "S, M, L, XL, XXL",
    status: "active",
    featured: false
  },
  {
    sku: "TS-BLK-9810",
    name: "New States Apparel Windbreaker 9810",
    series: "blank",
    seriesName: "NSA Blank Apparel",
    niche: "Jaket Windbreaker Tahan Angin & Gerimis",
    cititexCatId: 122,
    priceRetail: 189000,
    priceReseller: 165000,
    costBlank: 145000,
    costDtf: 0,
    costPress: 0,
    costPack: 3500,
    costOverhead: 1500,
    filePath: "https://cititex.com/api/uploads/category/album/front_side/122-Black.jpg",
    description: "Jaket windbreaker New States Apparel 9810. Bahan poliester parasut premium tahan terpaan angin dan gerimis ringan. Ringan, praktis dilipat, dilengkapi resleting kokoh dan tudung kepala.",
    colors: "Black, Maroon, Navy, Forest Camo, Black Camo, Black-Forest Camo, Black-Graphite, Light Blue, Light Pink",
    sizes: "S, M, L, XL, XXL",
    status: "active",
    featured: false
  },
  {
    sku: "TS-BLK-9820",
    name: "New States Apparel Coaches Jacket 9820",
    series: "blank",
    seriesName: "NSA Blank Apparel",
    niche: "Jaket Coach Streetwear Kancing Snap",
    cititexCatId: 123,
    priceRetail: 199000,
    priceReseller: 175000,
    costBlank: 155000,
    costDtf: 0,
    costPress: 0,
    costPack: 3500,
    costOverhead: 1500,
    filePath: "https://cititex.com/api/uploads/category/album/front_side/123-Black.jpg",
    description: "Jaket coach New States Apparel 9820 dengan kerah lipat dan kancing snap depan. Tampilan streetwear klasik vintage yang sangat populer di kalangan komunitas kreatif.",
    colors: "Black, Maroon, Navy, Forest Camo, Black Camo",
    sizes: "S, M, L, XL, XXL",
    status: "active",
    featured: false
  },
  {
    sku: "TS-BLK-5480",
    name: "New States Apparel Heavyweight Long Sleeve 5480",
    series: "blank",
    seriesName: "NSA Blank Apparel",
    niche: "Kaos Polos Lengan Panjang 20s Heavy",
    cititexCatId: 124,
    priceRetail: 89000,
    priceReseller: 78000,
    costBlank: 72000,
    costDtf: 0,
    costPress: 0,
    costPack: 3500,
    costOverhead: 1500,
    filePath: "https://cititex.com/api/uploads/category/album/front_side/124-White.jpg",
    description: "Kaos lengan panjang New States Apparel Heavyweight 5480. Bahan tebal 20s, potongan boxier fit dengan manset rib rapat. Sangat dicari untuk gaya streetwear musim sejuk.",
    colors: "White, Black, Navy, Maroon, Sport Grey, Red, Royal Blue, Gold",
    sizes: "S, M, L, XL, XXL",
    status: "active",
    featured: false
  },
  {
    sku: "TS-BLK-9830",
    name: "New States Apparel Bomber Jacket 9830",
    series: "blank",
    seriesName: "NSA Blank Apparel",
    niche: "Jaket Bomber Militer Distro Tebal",
    cititexCatId: 127,
    priceRetail: 215000,
    priceReseller: 185000,
    costBlank: 165000,
    costDtf: 0,
    costPress: 0,
    costPack: 3500,
    costOverhead: 1500,
    filePath: "https://cititex.com/api/uploads/category/album/front_side/127-Black.jpg",
    description: "Jaket bomber New States Apparel 9830. Lapisan nilon tebal dengan furing lembut, resleting lengan khas flight jacket, serta rib elastis pada leher dan pergelangan tangan.",
    colors: "Black, Army, Black-White",
    sizes: "S, M, L, XL, XXL",
    status: "active",
    featured: false
  },
  {
    sku: "TS-BLK-72Y00",
    name: "New States Apparel Youth T-Shirt 72Y00",
    series: "blank",
    seriesName: "NSA Blank Apparel",
    niche: "Kaos Polos Anak Combed 24s",
    cititexCatId: 129,
    priceRetail: 47000,
    priceReseller: 40000,
    costBlank: 35000,
    costDtf: 0,
    costPress: 0,
    costPack: 3500,
    costOverhead: 1500,
    filePath: "https://cititex.com/api/uploads/category/album/front_side/129-Black.jpg",
    description: "Kaos polos anak New States Apparel 72Y00. 100% Cotton Combed 24s ramah kulit anak, tidak gerah dan halus. Didesain dengan ukuran proporsional usia 2-14 tahun.",
    colors: "Black, White, Navy, Sport Grey, Red, Royal Blue, Gold, Light Pink, Daisy, Carolina Blue, Heliconia, Irish Green, Lime, Orange, Maroon, Green Ash, Aqua Sky, Salmon, Purple, Butter, Forest Green, Sand, Military Green, Chestnut, Dark Chocolate, Mustard, Sapphire, Black Heather, Burgundy Heather, Dark Green Heather, Navy Heather, Red Heather, Lilac, Charcoal",
    sizes: "XS, S, M, L, XL",
    status: "active",
    featured: false
  },
  {
    sku: "TS-BLK-2700",
    name: "New States Apparel Dri-Fit 2700",
    series: "blank",
    seriesName: "NSA Blank Apparel",
    niche: "Kaos Olahraga Micro-Mesh Quick-Dry",
    cititexCatId: 130,
    priceRetail: 47000,
    priceReseller: 40000,
    costBlank: 35000,
    costDtf: 0,
    costPress: 0,
    costPack: 3500,
    costOverhead: 1500,
    filePath: "https://cititex.com/api/uploads/category/album/front_side/130-Black.jpg",
    description: "Kaos olahraga New States Apparel Dri-Fit 2700. 100% micro-mesh polyester yang sangat ringan dan cepat menyerap keringat. Ideal untuk gym, lari, futsal, dan aktivitas outdoor.",
    colors: "Black, Charcoal, Gold, Navy, Neon Green, Red, Royal Blue, White",
    sizes: "S, M, L, XL, XXL",
    status: "active",
    featured: false
  },
  {
    sku: "TS-BLK-2720",
    name: "New States Apparel Dri-Fit Curved Hem 2720",
    series: "blank",
    seriesName: "NSA Blank Apparel",
    niche: "Kaos Sport Dri-Fit Curved Hem Modern",
    cititexCatId: 138,
    priceRetail: 49000,
    priceReseller: 42000,
    costBlank: 38000,
    costDtf: 0,
    costPress: 0,
    costPack: 3500,
    costOverhead: 1500,
    filePath: "https://cititex.com/api/uploads/category/album/front_side/138-White.jpg",
    description: "Kaos olahraga New States Apparel 2720 dengan potongan bawah melengkung (curved hem) modern. Bahan polyester dri-fit sejuk dan elastis dengan puluhan pilihan warna dinamis.",
    colors: "White, Sapphire, Red, Royal Blue, Orange, Navy, Neon Green, Aqua Sky, Maroon, Military Green, Black, Light Pink, Carolina Blue, Charcoal, Lilac, Irish Green, Dark Chocolate, Daisy, Heliconia, Forest Green, Gold, Green Ash, Butter, Chestnut, Mustard, Purple, Salmon, Sand",
    sizes: "S, M, L, XL, XXL",
    status: "active",
    featured: false
  },
  {
    sku: "TS-BLK-8165",
    name: "New States Apparel Easy Care Polo 8165",
    series: "blank",
    seriesName: "NSA Blank Apparel",
    niche: "Wangki Polo CVC Anti Kusut",
    cititexCatId: 139,
    priceRetail: 79000,
    priceReseller: 69000,
    costBlank: 62000,
    costDtf: 0,
    costPress: 0,
    costPack: 3500,
    costOverhead: 1500,
    filePath: "https://cititex.com/api/uploads/category/album/front_side/139-White.jpg",
    description: "Baju polo New States Apparel Easy Care 8165. Terbuat dari bahan CVC pique piringan halus yang tahan kusut dan cepat kering. Sangat awet untuk seragam dan pemakaian harian.",
    colors: "White, Sport Grey, Red, Royal Blue, Orange, Navy, Maroon, Light Pink, Irish Green, Forest Green, Daisy, Charcoal, Carolina Blue, Black, Dark Chocolate, Gold, Military Green, Sand",
    sizes: "S, M, L, XL, XXL, 3XL",
    status: "active",
    featured: false
  }
];

export const SEED_ORDERS = [
  {
    id: "SHP-2609-001",
    customer: "Dimas Arya",
    phone: "0812-9821-4411",
    city: "Jakarta Selatan",
    channel: "shopee",
    sku: "TS-PRO-001",
    productName: "Commit & Pray",
    garment: "NSA Softstyle 30s",
    color: "Hitam",
    size: "L",
    qty: 1,
    price: 99000,
    fee: 6435,
    status: "pending",
    date: "2026-09-04 14:20"
  },
  {
    id: "SHP-2609-002",
    customer: "Reza Fahlevi",
    phone: "0857-1122-3344",
    city: "Bandung",
    channel: "shopee",
    sku: "TS-KOM-001",
    productName: "7 Summits 3000 MDPL",
    garment: "NSA Softstyle 30s",
    color: "Olive",
    size: "XL",
    qty: 1,
    price: 99000,
    fee: 6435,
    status: "dtf",
    date: "2026-09-04 15:10"
  },
  {
    id: "WA-2609-003",
    customer: "Komunitas Kopi Pagi",
    phone: "0818-4455-6677",
    city: "Yogyakarta",
    channel: "whatsapp",
    sku: "TS-REC-001",
    productName: "Crisis with Iced Coffee",
    garment: "NSA Heavyweight 24s",
    color: "Krem",
    size: "M",
    qty: 2,
    price: 210000,
    fee: 0,
    status: "press",
    date: "2026-09-04 16:05"
  },
  {
    id: "WEB-2609-004",
    customer: "Andi Wijaya",
    phone: "0821-8899-0011",
    city: "Surabaya",
    channel: "web",
    sku: "TS-LOK-001",
    productName: "Wong Jowo Ojo Ilang",
    garment: "NSA Softstyle 30s",
    color: "Hitam",
    size: "L",
    qty: 1,
    price: 89000,
    fee: 1335,
    status: "pack",
    date: "2026-09-04 17:45"
  }
];

export const INITIAL_INVENTORY_MATRIX = {
  nsa_softstyle_30s: {
    Hitam:      { S: 4, M: 8, L: 10, XL: 6, XXL: 3, "3XL": 2 },
    Krem:       { S: 2, M: 5, L: 6,  XL: 4, XXL: 2, "3XL": 1 },
    Charcoal:   { S: 3, M: 4, L: 5,  XL: 3, XXL: 1, "3XL": 1 },
    Olive:      { S: 2, M: 4, L: 5,  XL: 3, XXL: 2, "3XL": 1 },
    Navy:       { S: 2, M: 3, L: 4,  XL: 2, XXL: 1, "3XL": 1 },
    Terracotta: { S: 1, M: 3, L: 4,  XL: 2, XXL: 1, "3XL": 0 },
    Putih:      { S: 3, M: 6, L: 6,  XL: 4, XXL: 2, "3XL": 1 }
  },
  nsa_heavyweight_24s: {
    Hitam:    { S: 3, M: 6, L: 8, XL: 5, XXL: 2, "3XL": 1 },
    Krem:     { S: 2, M: 4, L: 5, XL: 3, XXL: 1, "3XL": 1 },
    Charcoal: { S: 2, M: 3, L: 4, XL: 2, XXL: 1, "3XL": 1 },
    Olive:    { S: 1, M: 2, L: 3, XL: 2, XXL: 1, "3XL": 0 },
    Navy:     { S: 1, M: 2, L: 3, XL: 1, XXL: 1, "3XL": 0 }
  },
  nsa_longsleeve: {
    Hitam:    { S: 2, M: 4, L: 5, XL: 3, XXL: 1, "3XL": 1 },
    Putih:    { S: 1, M: 3, L: 3, XL: 2, XXL: 1, "3XL": 0 },
    Navy:     { S: 1, M: 2, L: 2, XL: 1, XXL: 1, "3XL": 0 },
    Charcoal: { S: 1, M: 2, L: 2, XL: 1, XXL: 0, "3XL": 0 }
  },
  nsa_hoodie: {
    Hitam:    { S: 1, M: 3, L: 4, XL: 3, XXL: 1, "3XL": 1 },
    Charcoal: { S: 1, M: 2, L: 2, XL: 2, XXL: 1, "3XL": 0 },
    Navy:     { S: 0, M: 2, L: 2, XL: 1, XXL: 1, "3XL": 0 }
  },
  nsa_polo: {
    Hitam: { S: 2, M: 3, L: 4, XL: 2, XXL: 1, "3XL": 1 },
    Navy:  { S: 1, M: 2, L: 3, XL: 2, XXL: 1, "3XL": 0 },
    Putih: { S: 1, M: 2, L: 2, XL: 1, XXL: 1, "3XL": 0 }
  },
  supplies: {
    "Polymailer Tebal (30x40 cm)": { Ready: 120, Min: 30 },
    "Hangtag Distro TeeStock":     { Ready: 250, Min: 50 },
    "Stiker Vinyl Pack TeeStock":  { Ready: 180, Min: 40 },
    "Kertas Roti Baking Paper":    { Ready: 45,  Min: 10 },
    "Lakban Fragile Merah":        { Ready: 6,   Min: 2  }
  },
  dtf_films: {
    "TS-PRO-001": { name: "Commit & Pray", size: "A3 (30x40 cm)", ready: 4, min: 2, unitCost: 12000, category: "graphic" },
    "TS-PRO-002": { name: "Architect's Blueprint", size: "A3 (30x40 cm)", ready: 2, min: 2, unitCost: 12000, category: "graphic" },
    "TS-KOM-001": { name: "7 Summits 3000 MDPL", size: "A3 (30x40 cm)", ready: 3, min: 2, unitCost: 12000, category: "graphic" },
    "TS-LOK-001": { name: "Wong Jowo Ojo Ilang", size: "A3 (30x40 cm)", ready: 2, min: 2, unitCost: 12000, category: "graphic" },
    "TS-REC-001": { name: "Crisis with Iced Coffee", size: "A3 (30x40 cm)", ready: 1, min: 2, unitCost: 12000, category: "graphic" },
    "TS-FAN-001": { name: "Neo Tokyo 1988", size: "A3 (30x40 cm)", ready: 3, min: 2, unitCost: 12000, category: "graphic" },
    "ACC-LABEL-NECK": { name: "Label Kerah Dalam TeeStock", size: "Kecil (6x3 cm)", ready: 24, min: 10, unitCost: 1000, category: "accessory" },
    "ACC-LOGO-CHEST": { name: "Logo Dada Saku TeeStock", size: "Saku (8x8 cm)", ready: 12, min: 5, unitCost: 1500, category: "accessory" }
  }
};
